// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/jobs": {
            "get": {
                "description": "View history of tasks and their status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "job-engine"
                ],
                "summary": "List all scraping tasks",
                "parameters": [
                    {
                        "enum": [
                            "pending",
                            "processing",
                            "completed",
                            "failed"
                        ],
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Number of jobs to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Number of jobs to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ScrapingJob"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "🔥 **SUPER EASY MODE**: Just send { \"url\": \"...\" } and we will scrape everything on that page automatically.\n🛠️ **CUSTOM MODE**: Provide \"actions\" (navigate, click, extract, etc.) for complex workflows.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs-management"
                ],
                "summary": "[🔥 Scrape All] or Custom Task",
                "parameters": [
                    {
                        "description": "Request Body (Try just { \\",
                        "name": "job",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateJobRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.ScrapingJob"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/jobs/{id}": {
            "get": {
                "description": "Get full details of a specific task",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "job-engine"
                ],
                "summary": "Check task status/details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ScrapingJob"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/jobs/{id}/result": {
            "get": {
                "description": "Retrieve the final data/results of a completed task",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "results-delivery"
                ],
                "summary": "Fetch scraped data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ScrapingResult"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/queue/status": {
            "get": {
                "description": "See current queue load and engine status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system-health"
                ],
                "summary": "Monitor engine health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.QueueStatusResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ActionRequest": {
            "type": "object",
            "properties": {
                "options": {
                    "type": "object",
                    "additionalProperties": true
                },
                "target": {
                    "type": "string",
                    "example": "#search-input"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "navigate",
                        "click",
                        "type",
                        "wait",
                        "screenshot",
                        "extract",
                        "scroll"
                    ],
                    "example": "navigate"
                },
                "value": {
                    "type": "string",
                    "example": "search query"
                }
            }
        },
        "api.CreateJobRequest": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ActionRequest"
                    }
                },
                "max_retries": {
                    "type": "integer",
                    "example": 3
                },
                "timeout": {
                    "type": "integer",
                    "example": 30
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com"
                },
                "user_agent": {
                    "type": "string",
                    "example": "Mozilla/5.0..."
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "api.QueueStatusResponse": {
            "type": "object",
            "properties": {
                "is_running": {
                    "type": "boolean"
                },
                "queue_size": {
                    "type": "integer"
                }
            }
        },
        "models.ActionType": {
            "type": "string",
            "enum": [
                "navigate",
                "click",
                "type",
                "wait",
                "screenshot",
                "extract",
                "scroll"
            ],
            "x-enum-varnames": [
                "ActionNavigate",
                "ActionClick",
                "ActionType_",
                "ActionWait",
                "ActionScreenshot",
                "ActionExtract",
                "ActionScroll"
            ]
        },
        "models.JobAction": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "job_id": {
                    "type": "string"
                },
                "options": {
                    "type": "object",
                    "additionalProperties": true
                },
                "order": {
                    "type": "integer"
                },
                "target": {
                    "description": "CSS selector, URL, or text",
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/models.ActionType"
                },
                "value": {
                    "description": "Text to type, wait duration, etc.",
                    "type": "string"
                }
            }
        },
        "models.JobStatus": {
            "type": "string",
            "enum": [
                "pending",
                "processing",
                "completed",
                "failed"
            ],
            "x-enum-varnames": [
                "StatusPending",
                "StatusProcessing",
                "StatusCompleted",
                "StatusFailed"
            ]
        },
        "models.ScrapingJob": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.JobAction"
                    }
                },
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "max_retries": {
                    "type": "integer"
                },
                "result": {
                    "$ref": "#/definitions/models.ScrapingResult"
                },
                "retries": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/models.JobStatus"
                },
                "timeout": {
                    "description": "in seconds",
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "user_agent": {
                    "type": "string"
                }
            }
        },
        "models.ScrapingResult": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "id": {
                    "type": "string"
                },
                "job_id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "screenshots": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Distributed Web Scraper API",
	Description:      "Enterprise-grade distributed web scraping service with headless browser support.\n\n### 🚀 Quick Usage Guide:\n| Action Type | **Target** (Field) | **Value** (Field) | Description |\n| :--- | :--- | :--- | :--- |\n| **navigate** | Full URL (e.g., https://google.com) | - | Navigates the browser to the specified URL |\n| **click** | CSS Selector (e.g., #submit-btn) | - | Clicks on the element matching the selector |\n| **type** | CSS Selector (e.g., input[name='q']) | Text to type | Types text into an input field |\n| **wait** | - | Seconds (e.g., 5) | Pauses execution for specified seconds |\n| **extract** | CSS Selector (e.g., .price-tag) | Key Name | Extracts text and saves it to the result map with the given Key Name |\n| **screenshot** | - | - | Takes a full-page screenshot (base64) |\n| **scroll** | - | - | Scrolls down the page (options: x, y) |\n\n### 💡 Tips:\n- **CSS Selectors**: Use standard selectors like `.class`, `#id`, or `tag[attr='val']`.\n- **Results**: After a job is `completed`, fetch results from the `/result` endpoint.\n- **Headless**: All jobs run in a real headless Chrome instance.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
